#!/usr/bin/zsh

TOOLNAME="projector"

SCREENOUTPUT=eDP1
HDMIOUTPUT=HDMI1
VGAOUTPUT=DP2
EXTOUTPUT=""

# user input keywords
# These must all be lower case, because input is changed to lower case before comparing to these.
RESETCOMMAND="reset"
VGACOMMAND="vga"
HDMICOMMAND="hdmi"
DUPLICATECOMMAND="duplicate"
EXTENDCOMMAND="extend"
ONLYCOMMAND="only"

# takes any number of arguments, outputs to stdout
lower() {
    tr '[:upper:]' '[:lower:]' <<<"$*"
}

fail() {
    echo "USAGE:"
    echo "$TOOLNAME $RESETCOMMAND"
    # echo "projector reset"
    echo "or"
    echo "$TOOLNAME ($VGACOMMAND|$HDMICOMMAND) [$DUPLICATECOMMAND|$EXTENDCOMMAND|$ONLYCOMMAND]"
    # echo "projector (vga|hdmi) [duplicate|extend|only)]
    exit 1
}

turnon() {
    xrandr --output "$1" --auto
}

turnoff() {
    xrandr --output "$1" --off
}

case $# in
    1 | 2)
        case `lower $1` in
            $RESETCOMMAND)
                echo "reseting"
                echo $SCREENOUTPUT
                turnon $SCREENOUTPUT
                turnoff $HDMIOUTPUT
                turnoff $VGAOUTPUT
                exit 0
                ;;
            $VGACOMMAND)
                EXTOUTPUT=$VGAOUTPUT
                ;;
            $HDMICOMMAND)
                EXTOUTPUT=$HDMIOUTPUT
                ;;
            *)
                fail
                ;;
        esac
        case `lower $2` in
            $EXTENDCOMMAND)
                echo "set $EXTOUTPUT to extend"
                echo "Not supported yet"
                ;;
            $DUPLICATECOMMAND)
                echo "set $EXTOUTPUT to duplicate"
                turnon $SCREENOUTPUT
                turnon $EXTOUTPUT
                ;;
            '' | $ONLYCOMMAND)
                echo "set $EXTOUTPUT to only"
                turnoff $SCREENOUTPUT
                turnon $EXTOUTPUT
                ;;
            *)
                fail
                ;;
        esac
        ;;
    *)
        fail
        ;;
esac
